#!/bin/sh
# Patch the image's default e2guardian.conf before starting.
# We do NOT replace the file — the default ships with all required list/story
# references. We only change the settings that differ for our deployment.
set -e

E2G_CONF="/etc/e2guardian/e2guardian.conf"
E2G_F1="/etc/e2guardian/e2guardianf1.conf"

# Replace a setting if it exists, or append it if not.
# Handles both "key = value" and commented-out "#key = value" lines.
set_conf() {
  grep -vE "^#?${2}[[:space:]]*=" "${1}" > /tmp/e2g_patch.conf
  printf '%s = %s\n' "${2}" "${3}" >> /tmp/e2g_patch.conf
  cp /tmp/e2g_patch.conf "${1}"
}

# ── Feature toggles (from .env via docker-compose environment:) ───────────────
E2G_CONTENT_FILTER="${E2G_CONTENT_FILTER:-on}"
E2G_SITE_BLOCK="${E2G_SITE_BLOCK:-on}"
E2G_SSL_MITM="${E2G_SSL_MITM:-on}"
E2G_BYPASS="${E2G_BYPASS:-off}"

printf '[start.sh] content_filter=%s  site_block=%s  ssl_mitm=%s  bypass=%s\n' \
  "${E2G_CONTENT_FILTER}" "${E2G_SITE_BLOCK}" "${E2G_SSL_MITM}" "${E2G_BYPASS}"

# ── Upstream proxy ────────────────────────────────────────────────────────────
# proxyip requires an IP address (not a hostname). Resolve "squid" via Docker DNS at startup.
# Remove any stale parent*/proxy* variants that accumulated from earlier attempts.
grep -vE "^(parentproxy|parentip|parentport)[[:space:]]*=" "${E2G_CONF}" > /tmp/e2g_patch.conf
cp /tmp/e2g_patch.conf "${E2G_CONF}"
SQUID_IP=$(getent hosts squid | awk '{ print $1 }')
set_conf "${E2G_CONF}" proxyip    "${SQUID_IP}"
set_conf "${E2G_CONF}" proxyport  3128

# ── Foreground mode (required for Docker) ────────────────────────────────────
set_conf "${E2G_CONF}" nodaemon   on

# ── Access log ────────────────────────────────────────────────────────────────
# set_accesslog = 'stderr' is the only destination that reliably works in this
# e2guardian build — file-path destinations are silently ignored.
# A FIFO + tee (see end of script) mirrors stderr to the named volume so filebeat
# can read it, while still keeping output visible in docker logs.
grep -vE "^#?set_accesslog[[:space:]]*=" "${E2G_CONF}" > /tmp/e2g_patch.conf
printf "set_accesslog = 'stderr'\n" >> /tmp/e2g_patch.conf
cp /tmp/e2g_patch.conf "${E2G_CONF}"

# ── SSL MITM ──────────────────────────────────────────────────────────────────
# cert-init pre-generates ca.crt, ca.key, cert.key into /certs.
# Import ./e2guardian/certs/ca.crt into your OS/browser trust store.
mkdir -p /tmp/e2g-generated-certs

set_conf "${E2G_CONF}" cacertificatepath "'/certs/ca.crt'"             # CA signing cert
set_conf "${E2G_CONF}" caprivatekeypath  "'/certs/ca.key'"             # CA private key
set_conf "${E2G_CONF}" certprivatekeypath "'/certs/cert.key'"          # per-domain cert key
set_conf "${E2G_CONF}" generatedcertpath "'/tmp/e2g-generated-certs'"  # writable runtime dir

if [ "${E2G_SSL_MITM}" = "on" ]; then
  set_conf "${E2G_CONF}" enablessl      on
  set_conf "${E2G_F1}"   sslmitm        on
  set_conf "${E2G_F1}"   mitmcheckcert  on
else
  set_conf "${E2G_CONF}" enablessl      off
  set_conf "${E2G_F1}"   sslmitm        off
fi

# ── Content filtering ─────────────────────────────────────────────────────────
# naughtynesslimit: score threshold before a page is blocked.
# 50 = default (normal filtering), 9999 = effectively disables phrase scoring.
if [ "${E2G_CONTENT_FILTER}" = "on" ]; then
  set_conf "${E2G_F1}" naughtynesslimit 50
else
  set_conf "${E2G_F1}" naughtynesslimit 9999
fi

# ── Bypass ────────────────────────────────────────────────────────────────────
# bypass = 1 lets users click through a block page; 0 = hard block, no bypass.
if [ "${E2G_BYPASS}" = "on" ]; then
  set_conf "${E2G_F1}" bypass 1
else
  set_conf "${E2G_F1}" bypass 0
fi

# ── Generate site.story ───────────────────────────────────────────────────────
# common.story's bannedcheck only calls urlin (URL lists), missing site-level bans.
# We override it here to also call sitein (site lists) when site blocking is on.
# This file is written fresh on every start so the toggles take effect immediately.
cat > /etc/e2guardian/site.story << 'STORY'
# Generated by start.sh — do not edit (overwritten on every container restart).

# Disable AV scanning (no AV plugin configured).
function(checknoscanlists)
function(checknoscantypes)
STORY

if [ "${E2G_SITE_BLOCK}" = "on" ]; then
  cat >> /etc/e2guardian/site.story << 'STORY'

# Site blocking on: check bannedsitelist (sitein) for HTTP requests.
# Overrides common.story's bannedcheck which only uses urlin (URL lists).
function(bannedcheck)
if(true) returnif checkblanketblock
if(sitein, banned) return setblock
if(urlin, banned) return setblock
ifnot(urlin,exceptionfile) returnif checkurlextension
if(useragentin, banneduseragent) return setblock
if(headerin, bannedheader) return setblock
STORY
fi

# ── Site lists ────────────────────────────────────────────────────────────────
# Injected via direct volume mounts at the paths the default config resolves.

# ── Launch ────────────────────────────────────────────────────────────────────
# Mirror e2guardian stderr to /var/log/e2guardian/access.log (for filebeat)
# while keeping it visible via docker logs (tee writes to stdout).
FIFO=/tmp/e2g_log_fifo
mkfifo "${FIFO}"
tee /var/log/e2guardian/access.log < "${FIFO}" &
exec e2guardian 2>"${FIFO}"
